name: demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  demo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.0', '7.4', '8.3']

    steps:
    - uses: shivammathur/setup-php@v2
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: ${{ matrix.php-versions }}
    - uses: actions/checkout@v3
    - name: Demo
      run: php a.php
